import { Task, EventItem, Habit, Activity, Goal, AIInsight, UserProfile } from '../types/models';

export const mockProfile: UserProfile = {
  id: 'usr-001',
  email: 'alex.rivera@kronos.os',
  fullName: 'Alex Rivera',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
  bio: 'Product Architect & Marathoner · Building high-leverage operating systems.',
  timezone: 'America/Los_Angeles',
  themePreference: 'dark',
  weeklyDistanceGoalKm: 35.0,
  dailyTaskGoal: 8,
  currentStreak: 19,
  totalActivitiesCount: 142,
};

export const mockTasks: Task[] = [
  {
    id: 'tsk-001',
    userId: 'usr-001',
    title: 'Review System Architecture PR #104',
    description: 'Verify RLS security policies, latency budgets, and token refresh handling.',
    dueDate: '2026-08-26',
    dueTime: '10:30',
    priority: 'urgent',
    status: 'completed',
    category: 'Engineering',
    estimatedMinutes: 45,
    actualMinutes: 40,
    completedAt: '2026-08-26T10:28:00Z',
    createdAt: '2026-08-25T14:00:00Z',
  },
  {
    id: 'tsk-002',
    userId: 'usr-001',
    title: 'Finalize Mobile Design Tokens & Dark Mode',
    description: 'Ensure contrast ratios conform to WCAG AAA standards across all components.',
    dueDate: '2026-08-26',
    dueTime: '13:00',
    priority: 'high',
    status: 'completed',
    category: 'Design',
    estimatedMinutes: 60,
    actualMinutes: 55,
    completedAt: '2026-08-26T12:50:00Z',
    createdAt: '2026-08-25T15:00:00Z',
  },
  {
    id: 'tsk-003',
    userId: 'usr-001',
    title: 'Quarterly Executive OKR Alignment',
    description: 'Prepare key metric slides for active user retention and speed scores.',
    dueDate: '2026-08-26',
    dueTime: '15:30',
    priority: 'medium',
    status: 'completed',
    category: 'Strategy',
    estimatedMinutes: 30,
    completedAt: '2026-08-26T15:25:00Z',
    createdAt: '2026-08-26T08:00:00Z',
  },
  {
    id: 'tsk-004',
    userId: 'usr-001',
    title: 'Deep Work: Core Engine Refactor',
    description: 'Optimize data flow synchronization between local store and backend.',
    dueDate: '2026-08-26',
    dueTime: '18:00',
    priority: 'urgent',
    status: 'in_progress',
    category: 'Deep Work',
    estimatedMinutes: 90,
    createdAt: '2026-08-26T09:00:00Z',
  },
  {
    id: 'tsk-005',
    userId: 'usr-001',
    title: 'Zone-2 Base Aerobic Run (5 km)',
    description: 'Keep heart rate below 145 bpm. Focus on cadence and rhythm.',
    dueDate: '2026-08-26',
    dueTime: '19:30',
    priority: 'high',
    status: 'pending',
    category: 'Fitness',
    estimatedMinutes: 35,
    createdAt: '2026-08-26T07:00:00Z',
  },
  {
    id: 'tsk-006',
    userId: 'usr-001',
    title: 'Hydration & Post-Run Mobility Stretching',
    description: '15 minutes foam rolling + hamstring and hip flexor stretches.',
    dueDate: '2026-08-26',
    dueTime: '20:15',
    priority: 'low',
    status: 'pending',
    category: 'Recovery',
    estimatedMinutes: 20,
    createdAt: '2026-08-26T07:00:00Z',
  },
];

export const mockEvents: EventItem[] = [
  {
    id: 'evt-001',
    userId: 'usr-001',
    title: 'Morning Routine & Intention Setting',
    description: 'Journaling, hydration, daily priority review.',
    startTime: '2026-08-26T07:00:00Z',
    endTime: '2026-08-26T08:00:00Z',
    isAllDay: false,
    color: '#34D399', // Emerald Wellness
    category: 'Wellness',
  },
  {
    id: 'evt-002',
    userId: 'usr-001',
    title: 'Product Engineering Sync',
    description: 'Sprint planning and blocker resolution.',
    startTime: '2026-08-26T10:00:00Z',
    endTime: '2026-08-26T11:00:00Z',
    isAllDay: false,
    location: 'Google Meet',
    color: '#4F8CFF', // Blue Work
    category: 'Work',
  },
  {
    id: 'evt-003',
    userId: 'usr-001',
    title: 'Deep Work: Core Engine Refactor',
    description: 'Project development block without interruptions.',
    startTime: '2026-08-26T18:00:00Z',
    endTime: '2026-08-26T19:15:00Z',
    isAllDay: false,
    color: '#4F8CFF', // Blue Deep Work
    category: 'Deep Work',
  },
  {
    id: 'evt-004',
    userId: 'usr-001',
    title: 'Evening Base Run (5 KM)',
    description: 'Coastal trail loop.',
    startTime: '2026-08-26T19:30:00Z',
    endTime: '2026-08-26T20:15:00Z',
    isAllDay: false,
    location: 'Bay Trail North Entrance',
    color: '#38BDF8', // Cyan Fitness
    category: 'Fitness',
  },
];

export const mockHabits: Habit[] = [
  {
    id: 'hab-001',
    userId: 'usr-001',
    title: 'Morning Sunlight & Hydration',
    description: '10 min direct sunlight + 500ml mineral water',
    category: 'Health',
    targetDaysPerWeek: 7,
    frequency: 'daily',
    color: '#38BDF8',
    icon: 'sun',
    currentStreak: 24,
    bestStreak: 45,
    isArchived: false,
    completedToday: true,
  },
  {
    id: 'hab-002',
    userId: 'usr-001',
    title: 'Deep Work Focus Block (90m)',
    description: 'No notifications, single-tasking flow',
    category: 'Productivity',
    targetDaysPerWeek: 5,
    frequency: 'daily',
    color: '#4F8CFF',
    icon: 'zap',
    currentStreak: 12,
    bestStreak: 28,
    isArchived: false,
    completedToday: true,
  },
  {
    id: 'hab-003',
    userId: 'usr-001',
    title: 'Daily Aerobic Activity / Run',
    description: 'Minimum 30 minutes moving at Zone 2',
    category: 'Fitness',
    targetDaysPerWeek: 6,
    frequency: 'daily',
    color: '#38BDF8',
    icon: 'activity',
    currentStreak: 18,
    bestStreak: 30,
    isArchived: false,
    completedToday: true,
  },
  {
    id: 'hab-004',
    userId: 'usr-001',
    title: 'Read 20 Pages of Non-Fiction',
    description: 'Systems thinking, biology, or software design',
    category: 'Mindset',
    targetDaysPerWeek: 7,
    frequency: 'daily',
    color: '#34D399',
    icon: 'book-open',
    currentStreak: 7,
    bestStreak: 21,
    isArchived: false,
    completedToday: true,
  },
  {
    id: 'hab-005',
    userId: 'usr-001',
    title: 'Zero Screen Time 1h Before Bed',
    description: 'Blue-light block and restorative wind-down',
    category: 'Sleep',
    targetDaysPerWeek: 7,
    frequency: 'daily',
    color: '#8B7CFF',
    icon: 'moon',
    currentStreak: 5,
    bestStreak: 14,
    isArchived: false,
    completedToday: false,
  },
];

export const mockActivities: Activity[] = [
  {
    id: 'act-001',
    userId: 'usr-001',
    title: 'Sunset Coastal Tempo Run',
    sportType: 'running',
    distanceMeters: 5240, // 5.24 km
    durationSeconds: 1902, // 31:42
    movingTimeSeconds: 1840,
    avgSpeedMps: 2.85, // 5:50 /km
    maxSpeedMps: 3.42,
    avgHeartRate: 154,
    maxHeartRate: 172,
    calories: 395,
    elevationGainMeters: 48,
    startedAt: '2026-08-25T19:15:00Z',
    completedAt: '2026-08-25T19:47:00Z',
    notes: 'Crisp evening breeze. Effortless through km 3-4.',
  },
  {
    id: 'act-002',
    userId: 'usr-001',
    title: 'Early Morning Aerobic Intervals',
    sportType: 'running',
    distanceMeters: 8400, // 8.40 km
    durationSeconds: 2880, // 48:00
    movingTimeSeconds: 2790,
    avgSpeedMps: 3.01, // 5:32 /km
    maxSpeedMps: 4.10,
    avgHeartRate: 162,
    maxHeartRate: 181,
    calories: 640,
    elevationGainMeters: 92,
    startedAt: '2026-08-24T06:30:00Z',
    completedAt: '2026-08-24T07:18:00Z',
    notes: '5x1km threshold intervals on flat gravel path.',
  },
  {
    id: 'act-003',
    userId: 'usr-001',
    title: 'Twin Peaks Scenic Road Ride',
    sportType: 'cycling',
    distanceMeters: 24600, // 24.6 km
    durationSeconds: 3420, // 57:00
    movingTimeSeconds: 3280,
    avgSpeedMps: 7.5, // 27.0 km/h
    maxSpeedMps: 13.8,
    avgHeartRate: 144,
    maxHeartRate: 168,
    calories: 580,
    elevationGainMeters: 380,
    startedAt: '2026-08-23T08:00:00Z',
    completedAt: '2026-08-23T08:57:00Z',
    notes: 'Climbed Twin Peaks before traffic picked up.',
  },
  {
    id: 'act-004',
    userId: 'usr-001',
    title: 'Redwood Valley Active Recovery Walk',
    sportType: 'walking',
    distanceMeters: 4120, // 4.12 km
    durationSeconds: 2580, // 43:00
    movingTimeSeconds: 2520,
    avgSpeedMps: 1.63,
    maxSpeedMps: 1.95,
    avgHeartRate: 98,
    calories: 195,
    elevationGainMeters: 32,
    startedAt: '2026-08-22T17:20:00Z',
    completedAt: '2026-08-22T18:03:00Z',
    notes: 'Podcast walk in the park.',
  },
];

export const mockGoals: Goal[] = [
  {
    id: 'gol-001',
    userId: 'usr-001',
    title: 'Sub 1:45 Half Marathon',
    description: 'Targeting Pacific Coast Half Marathon in October.',
    targetValue: 105,
    currentValue: 112,
    unit: 'min',
    deadline: '2026-10-18',
    category: 'Fitness',
    status: 'active',
  },
  {
    id: 'gol-002',
    userId: 'usr-001',
    title: 'Ship Life OS v1.0 Foundation',
    description: 'Complete UI system, offline store, database schemas and auth.',
    targetValue: 100,
    currentValue: 85,
    unit: '%',
    deadline: '2026-09-01',
    category: 'Career',
    status: 'active',
  },
  {
    id: 'gol-003',
    userId: 'usr-001',
    title: 'Consistent 30-Day Sleep Routine',
    description: 'Maintain 7.5+ hours sleep and early rising.',
    targetValue: 30,
    currentValue: 19,
    unit: 'days',
    deadline: '2026-09-10',
    category: 'Wellness',
    status: 'active',
  },
];

export const mockAIInsights: AIInsight[] = [
  {
    id: 'ins-001',
    type: 'schedule',
    title: 'Optimal Fitness Window',
    message: 'You have a free 45-minute window before dinner. Shifting your run to 6:30 PM avoids evening temperatures.',
    actionText: 'Adjust Schedule',
    confidenceScore: 0.94,
    createdAt: '2026-08-26T08:30:00Z',
  },
  {
    id: 'ins-002',
    type: 'focus',
    title: 'Peak Cognitive State',
    message: 'Highest focus output occurs between 18:00 - 19:30. "Core Engine Refactor" is queued for this block.',
    actionText: 'Enter Focus',
    confidenceScore: 0.89,
    createdAt: '2026-08-26T12:00:00Z',
  },
];
